--- # Lock Down Server
- name: Disallow Password Authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: "{{ hostvars['localhost']['target_state'] }}"
  notify: Restart sshd

- name: Disallow root SSH Access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: "{{ hostvars['localhost']['target_state'] }}"
  notify: Restart sshd
