---
- name: Set target_state for playbook
  set_fact:
    cacheable: yes
    target_state: "{{ target_state }}"

- name: Get localhost external ip address
  ipify_facts:
  register: external_ip_address

- name: Set localhost_external_ip_address for playbook
  set_fact:
    cacheable: yes
    localhost_external_ip_address: "{{ external_ip_address.ansible_facts.ipify_public_ip }}"

- name: Set certbot_email_address for playbook
  set_fact:
    cacheable: yes
    certbot_email_address: "{{ lookup('ini', 'certbot_email_address section=secrets file=./secrets.ini') }}"

- name: Set DNS for playbook
  set_fact:
    cacheable: yes
    domain_name: "{{ lookup('ini', 'domain_name section=configuration file=./secrets.ini') }}"
    subdomain_name: "{{ lookup('ini', 'subdomain_name section=configuration file=./secrets.ini') }}"

- name: Set AWS Credential Section
  set_fact:
    cacheable: yes
    aws_creds_section: "{{ lookup('ini', 'aws_creds_section section=secrets file=./secrets.ini') }}"

- name: Set AWS Creds Lookups
  set_fact:
    cacheable: yes
    aws_access_key_lookup: "aws_access_key_id section={{ hostvars['localhost']['aws_creds_section'] }} file=~/.aws/credentials"
    aws_secret_key_lookup: "aws_secret_access_key section={{ hostvars['localhost']['aws_creds_section'] }} file=~/.aws/credentials"

- name: Set aws creds for playbook
  set_fact:
    cacheable: yes
    target_aws_access_key: "{{ lookup('ini', aws_access_key_lookup) }}"
    target_aws_secret_key: "{{ lookup('ini', aws_secret_key_lookup) }}"

- name: Set ec2_ssh_key_name for playbook
  set_fact:
    cacheable: yes
    ec2_ssh_key_name: "{{ lookup('ini', 'ec2_ssh_key_name section=secrets file=./secrets.ini') }}"

- name: Set pi facts for playbook
  set_fact:
    cacheable: yes
    pi_ip_address: "{{ lookup('ini', 'pi_ip_address section=raspberry_pi file=./secrets.ini') }}"
    pi_hostname: "{{ lookup('ini', 'pi_hostname section=raspberry_pi file=./secrets.ini') }}"
    pi_default_username: "{{ lookup('ini', 'pi_default_username section=raspberry_pi file=./secrets.ini') }}"
    pi_default_password: "{{ lookup('ini', 'pi_default_password section=raspberry_pi file=./secrets.ini') }}"    
    pi_admin_username: "{{ lookup('ini', 'pi_admin_username section=raspberry_pi file=./secrets.ini') }}"
    pi_admin_password: "{{ lookup('ini', 'pi_admin_password section=raspberry_pi file=./secrets.ini') }}"
    pi_programmer_username: "{{ lookup('ini', 'pi_programmer_username section=raspberry_pi file=./secrets.ini') }}"
    pi_programmer_password: "{{ lookup('ini', 'pi_programmer_password section=raspberry_pi file=./secrets.ini') }}"

- name: Set ssh_key_directory
  set_fact:
    cacheable: yes
    ssh_key_directory: "{{ lookup('ini', 'ssh_key_directory section=configuration file=./secrets.ini') }}"

# TODO we should only add if it is reachable... scp or some other test script to demonstrate we can connect with auth
- name: Add unsecure_pi to hosts list
  add_host:
    hostname: unsecure_pi
    ansible_ssh_host: "{{ hostvars['localhost']['pi_ip_address'] }}"
    ansible_ssh_user: "{{ hostvars['localhost']['pi_default_username'] }}"
    ansible_password: "{{ hostvars['localhost']['pi_default_password'] }}"
    ansible_ssh_common_args: '-o Preferredauthentications=password -o StrictHostKeyChecking=no'

- name: Add secured pi to hosts list
  add_host:
    hostname: secure_pi
    ansible_ssh_host: "{{ hostvars['localhost']['pi_ip_address'] }}"
    ansible_ssh_user: "{{ hostvars['localhost']['pi_admin_username'] }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    # TODO set key file
    # ansible_ssh_private_key_file: "{{ hostvars['localhost']['admin_ssh_key_path'] }}/<set with stack name>"
  